name: items
description: todo
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  #angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+16
  #angular_components: ^0.13.0
  #http: ^0.12.0+2
  stream_transform: ^0.0.19
  #js: ^0.6.1+1

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.3.3
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  #mockito: ^4.1.0
  pageloader: ^3.2.0
